version: 0.2

env:
  variables:
    AWS_REGION: "eu-north-1"
    AWS_ACCOUNT_ID: "961894408879"
    ECR_REPO: "docker-ma7"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      - echo "Pre-build phase complete."
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
      - echo "Build phase complete."
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECR_REPO $ECR_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      - echo "Post-build phase complete."

artifacts:
  files:
    - imagedefinitions.json
